# preload = /home/yzuaf/Pictures/custom-wallpaper/nameless-photos-79YLZcD19PM.jpg
# wallpaper = eDP-1, /home/yzuaf/Pictures/custom-wallpaper/nameless-photos-79YLZcD19PM.jpg

preload = /home/yzuaf/Pictures/wallpaper.png

wallpaper {
    monitor = eDP-1
    path = /home/yzuaf/Pictures/wallpaper.png
}

