# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Monospace

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = eDP-1
    path = /home/yzuaf/Pictures/wallpaper.png
    blur_passes = 3
    blur_size = 4
    brightness = 0.85       # sedikit gelapin, biar elemen UI pop out
    contrast = 1.05
    vibrancy = 0
}

input-field {
    monitor =
    size = 22%, 5%

    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)

    # grayscale gradients, subtle tapi modern
    outer_color = rgba(ffffff55) rgba(888888dd) 90deg
    check_color = rgba(ccccccff) rgba(555555ff) 45deg
    fail_color = rgba(444444ff) rgba(888888ff) 25deg

    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# TIME (big, clean, white-ish)
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgb(230, 230, 230)

    position = -30, 0
    halign = right
    valign = top
}

# DATE (smaller, softer)
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font
    color = rgb(180, 180, 180)

    position = -30, -150
    halign = right
    valign = top
}


# KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 24
    font_family = $font
    color = rgb(200, 200, 200)
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}

